### ISSUE TITLE
internet-issues: Error: connect EHOSTUNREACH when server don't support ipv6.

### ISSUE THREAD

**Issue by MashiroSA** [ShizukuWorld/koishi-plugin-setu#3]
## Problem

Local test passed, but when I tried to fetch the plugin from my server and run the command "setu", it told me "发生未知错误".

Seems it cause by server running on ipv4 support only.

## Recurrence

- Install the v1.0.1 in koishi plugin market.
- Install the dependence.
- Run the command in group and got error.

## Log
```
2023-03-28T03:24:16: 2023-03-28 03:24:16 [W] command setu 
2023-03-28T03:24:16:                         Error: connect EHOSTUNREACH 2606:4700:3033::6815:356c:443
2023-03-28T03:24:16:                             at AxiosError.from (/root/rosemary-koishi-bot/node_modules/axios/dist/node/axios.cjs:725:14)
2023-03-28T03:24:16:                             at RedirectableRequest.handleRequestError (/root/rosemary-koishi-bot/node_modules/axios/dist/node/axios.cjs:2467:25)
2023-03-28T03:24:16:                             at RedirectableRequest.emit (node:events:513:28)
2023-03-28T03:24:16:                             at eventHandlers.<computed> (/root/rosemary-koishi-bot/node_modules/follow-redirects/index.js:14:24)
2023-03-28T03:24:16:                             at ClientRequest.emit (node:events:513:28)
2023-03-28T03:24:16:                             at TLSSocket.socketErrorListener (node:_http_client:502:9)
2023-03-28T03:24:16:                             at TLSSocket.emit (node:events:513:28)
2023-03-28T03:24:16:                             at emitErrorNT (node:internal/streams/destroy:151:8)
2023-03-28T03:24:16:                             at emitErrorCloseNT (node:internal/streams/destroy:116:3)
2023-03-28T03:24:16:                             at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

## PS
是的，当我改完代码发现我的生产环境不能用的时候，我仿佛被世界所丢弃😢

**Comment by MashiroSA** [comment]
拿到ipv6咯！
